# Generated by Django 4.2.6 on 2023-12-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contacts_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
